config/routes.rb
Rails.application.routes.draw do
  get "home", to: 'home#index'
  root "home#index"

  resources :people
  resources :clients do
    resources :contacts
    resources :invoices
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
	
  validates :kind_person, inclusion: { 
    in: %w(fisica juridica), 
    message: "admite solo los valores <<fisica>> o <<juridica>>" 
  }

  validates :cuil_cuit, uniqueness: { message: "ya existe en el sistema" }

  validates :cuil_cuit, format: { 
    with: /\A\d{2}-{1}\d{8}-{1}\d{1}\z/,
    message: "debe tener el formato XX-XXXXXXXX-X" 
  } 

  with_options if: :is_fisica? do |fisica|
    
    fisica.validates :name, :surname, :cuil_cuit, :birthday, :kind_document, :document, :gender, presence: true
    fisica.validates :document, numericality: { only_integers: true }
    fisica.validates :document, length: { minimum: 7, maximum: 9 }

    fisica.validates :name, :surname, 
      format:{ 
        with: /\A[a-zA-Z\s]+\z/,
        message: "sólo permite letras" 
      }

    fisica.validates :document, 
      uniqueness: { 
        scope: :kind_document, 
        message: "ya existe un numero con ese tipo de documento" 
      }
    
    fisica.validates :gender, 
      inclusion: { 
        in: %w(Masculino Femenino), 
        message: "admite los valores <<Femenino>> o <<Masculino>>" 
      }

    fisica.validates :kind_document, 
      inclusion: { 
        in: %w(DNI LE LC), 
        message: "admite solo los valores <<dni>>, <<lc>>, <<le>>" 
      } 
  end

  # ACLARACION: para las personas juridicas solo se valida que tengan:
    # name, birthday, cuil_cuit

  with_options if: :is_juridica? do |juridica|
    juridica.validates :name, :cuil_cuit, :birthday, presence: true
    juridica.validates :surname, :gender, :kind_document, :document, absence: true
  end
  
  def is_fisica?
    kind_person == "fisica"
  end

  def is_juridica?
    kind_person == "juridica"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :surname, :birthday, :gender, :kind_document, :document, :cuil_cuit, :kind_person)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
	def rellenar(param)
		param = "___" if param.nil? or param.size == 0
		param
	end
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_de_persona %><br>
    <%= f.select(:kind_person) do %>
      <% option = [ ["Selleccione...", ""], ["fisica", "fisica"], ["juridica", "juridica"]  ] %>
      <%= options_for_select(option) %>
    <% end %>

  </div>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :fecha_de_nacimiento %><br>
     <%= f.date_select(:birthday, { start_year: 1900, end_year: Date.today.year }) %>
  </div>
  <div class="field">
    <%= f.label :genero %><br>
    <%= f.select(:gender) do %>
      <% array = [ ["Seleccione...", ""], ["Masculino", "Masculino"], ["Femenino", "Femenino"] ] %>
      <%= options_for_select(array) %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :tipo_doc %><br>
    <%= f.select(:kind_document) do %>
      <% array = [ ["Seleccione...", ""], ["DNI", "DNI"], ["LE", "LE"], ["LC", "LC"] ] %>
      <%= options_for_select(array) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :documento %><br>
    <%= f.number_field :document %>
  </div>
  <div class="field">
    <%= f.label :cuil_cuit %><br>
    <%= f.text_field :cuil_cuit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'regresar', :back %>

app/views/people/edit.html.erb
<h1>Editar persona:</h1>
<h3><%= @person.name %> <%= @person.surname %> </h3>
<hr>
<%= render 'form' %>

<%= link_to 'Mostrar', @person %> |
<%= link_to 'Volver', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de personas</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Fecha de nacimiento</th>
      <th>Genero</th>
      <th>Tipo de documento</th>
      <th>Documento</th>
      <th>Cuil/Cuit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.kind_person %></td>
        <td><%= person.name %></td>
        <td><%= rellenar(person.surname) %></td>
        <td><%= person.birthday %></td>
        <td><%= rellenar(person.gender) %></td>
        <td><%= rellenar(person.kind_document) %></td>
        <td><%= rellenar(person.document) %></td>
        <td><%= person.cuil_cuit %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', home_path %> | <%= link_to 'Nueva Persona', new_person_path %>

app/views/people/new.html.erb
<h1>Nueva Persona</h1>

<%= render 'form' %>

<%= link_to 'Volver', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo de persona:</strong>
  <%= @person.kind_person %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= rellenar(@person.surname) %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<p>
  <strong>Gender:</strong>
  <%= rellenar(@person.gender) %>
</p>

<p>
  <strong>Kind document:</strong>
  <%= rellenar(@person.kind_document) %>
</p>

<p>
  <strong>Document:</strong>
  <%= rellenar(@person.document) %>
</p>

<p>
  <strong>Cuil cuit:</strong>
  <%= @person.cuil_cuit %>
</p>

<%= link_to 'Editar', edit_person_path(@person) %> |
<%= link_to 'Volver', people_path %>