config/routes.rb
Rails.application.routes.draw do
  get "home", to: 'home#index'
  root "home#index"

  resources :people
  resources :clients do
    resources :contacts
    resources :invoices
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :person
  belongs_to :client

  validates :person_id, :client_id, :date, :description, :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0, message: "solo se permite números positivos o el valr 0" }
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :set_client

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = @client.invoices
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = @client.invoices.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to client_invoice_path(@client, @invoice), notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to client_invoice_path(@client, @invoice), notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to client_invoices_path(@client), notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:description, :amount, :date, :person_id, :client_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for([@client, @invoice]) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :monto %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :fecha_de_emision %><br>
    <%= f.date_select(:date, { start_year: (2000), end_year: Date.today.year + 1 }) %>
  </div>
  <div class="field">
    <%= f.label :destinatario %><br>
    <%= f.select(:person_id) do %>
      <% people_array = Person.all.map { |person| ["#{person.name} #{person.cuil_cuit}", person.id] } %>
      <%= options_for_select(people_array) %>
    <% end %>

    <p> o ingrese una <%= link_to 'Nueva persona', new_person_path %> 

  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editar Factura</h1>

<%= render 'form' %>

<%= link_to 'Show', client_invoice_path(@client, @invoice) %> |
<%= link_to 'Back', client_invoices_path(@client) %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Facturas</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Monto</th>
      <th>Fecha de emision</th>
      <th>Destinatario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.description %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.date %></td>
        <td><%= invoice.person.name %>, <%= invoice.person.cuil_cuit %> </td>
        <td><%= link_to 'Mostrar', client_invoice_path(@client, invoice) %></td>
        <td><%= link_to 'Editar', edit_client_invoice_path(@client, invoice) %></td>
        <td><%= link_to 'Eliminar', client_invoice_path(@client, invoice), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva factra', new_client_invoice_path(@client) %> | 
<%= link_to 'Volver', client_path(@client) %> 

app/views/invoices/new.html.erb
<h1>Nueva Factura</h1>

<%= render 'form' %>

<%= link_to 'Volver', client_invoices_path(@client) %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @invoice.description %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @invoice.amount %>
</p>

<p>
  <strong>Fecha de emision:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Destinatario:</strong>
  <%= @invoice.person.name %>, <%= @invoice.person.cuil_cuit %>
</p>

<%= link_to 'Editar', edit_client_invoice_path(@client, @invoice) %> |
<%= link_to 'Volver', client_invoices_path(@client) %>