config/routes.rb
Rails.application.routes.draw do
  get "home", to: 'home#index'
  root "home#index"

  resources :people
  resources :clients do
    resources :contacts
    resources :invoices
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :contacts, dependent: :destroy
  has_many :invoices, dependent: :destroy
  has_many :people, through: :invoices

  #Validaciones
  validates :name, :surname, :cuil_cuit, :kind_document, :document, :gender, :birthday, presence: true
  
  validates :name, :surname, format: { 
    with: /\A[a-zA-Z\s]+\z/,
    message: "sólo permite letras" 
  }

  validates :cuil_cuit, uniqueness: { message: "ya existe en el sistema" }
  validates :cuil_cuit, format: { 
    with: /\A\d{2}-{1}\d{8}-{1}\d{1}\z/,
    message: "debe tener el formato XX-XXXXXXXX-X" 
  }

  validates :document, uniqueness: { 
    scope: :kind_document, 
    message: "ya existe un numero con este tipo de documento" }
  
  validates :document, numericality: { only_integers: true }
  validates :document, length: { minimum: 7, maximum: 9 }
  
  validates :gender, inclusion: { in: %w(Masculino Femenino), 
    message: "admite los valores <<Masculino>> o <<Femenino>>" } 

  validates :kind_document, inclusion: { 
    in: %w(DNI LE LC), 
    message: "admite solo los valores <<dni>>, <<lc>>, <<le>>" 
  }

  def client_age
      ((Date.current - birthday)/365).to_i
  end  

  def fac_per_people
    people
      .select("name, sum(amount) as sum_amount")
      .group(:id)
      .order("sum_amount DESC")
  end

  def count_fac_per_people
    people
      .select("name, count(amount) as tot_amount")
      .group(:id)
      .order("tot_amount DESC")
  end

  def fac_per_year
    invoices
      .select("strftime('%Y', date) as year, sum(amount) as total")
      .group("year")
      .order("year")
  end

  def fac_per_mouth
    invoices
      .select("strftime('%m', date) as mes, sum(amount) as total")
      .where("strftime('%Y', date) == strftime('%Y', 'now')")
      .group("mes")
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :surname, :birthday, :gender, :kind_document, :document, :cuil_cuit)
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :fecha_de_nacimiento %><br>
    <%= f.date_select(:birthday, { start_year: 1930, end_year: Date.today.year }) %>
  </div>
  <div class="field">
    <%= f.label :genero %><br>
    <%= f.select(:gender) do %>
      <% array = [ ["Masculino", "Masculino"], ["Femenino", "Femenino"] ] %>
      <%= options_for_select(array) %>
    <% end %> 
  </div>
  <div class="field">
    <%= f.label :tipo_de_documento %><br>
    <%= f.select(:kind_document) do %>
      <% array = [ ["DNI", "DNI"], ["LE", "LE"], ["LC", "LC"] ] %>
      <%= options_for_select(array) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :numero_de_documento %><br>
    <%= f.number_field :document %>
  </div>
  <div class="field">
    <%= f.label :Cuil_Cuit %><br>
    <%= f.text_field :cuil_cuit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar Cliente:</h1>
<h3> <%= @client.name %>, <%= @client.surname %> </h3>
<hr>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Fec nacimiento</th>
      <th>Genero</th>
      <th>Tipo Docum</th>
      <th>Documento</th>
      <th>Cuil/Cuit</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.surname %></td>
        <td><%= client.birthday %></td>
        <td><%= client.gender %></td>
        <td><%= client.kind_document %></td>
        <td><%= client.document %></td>
        <td><%= client.cuil_cuit %></td>
        <td><%= link_to 'mostrar', client %></td>
        <td><%= link_to 'Editar', edit_client_path(client) %></td>
        <td><%= link_to 'ver contactos', client_contacts_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'ver facturas', client_invoices_path(client) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', home_path %> | <%= link_to 'Nuevo Cliente', new_client_path %>

app/views/clients/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<h1> Infomacion de Contacto </h1>
<p>
  <%= link_to 'ver contactos', client_contacts_path(@client) %> | <%= link_to 'ver facturas emitidas', client_invoices_path(@client) %>
  <hr>
</p>


<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @client.surname %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @client.birthday %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @client.gender %>
</p>

<p>
  <strong>tipo de documento:</strong>
  <%= @client.kind_document %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @client.document %>
</p>

<p>
  <strong>Cuil/Cuit:</strong>
  <%= @client.cuil_cuit %>
</p>

  <p>
  <strong>Edad:</strong>
  <%= @client.client_age %>
</p>
<hr>
<h2>Facturacion por año:</h2>
  <% @client.fac_per_year.each do | p | %>
    <p> <%= "En el año #{p.year} el cliente facturó #{p.total}" %></p>
  <% end %>
<hr>
<h2>Cantidad de facturas por mes de este año:</h2>
  <% @client.fac_per_mouth.each do | p | %>
    <p> <%= "En el mes #{p.mes} el cliente emitió #{p.total} facturas" %></p>
  <% end %>
<hr>
<h2>Personas a las que mas facturas les facturó:</h2>
  <% @client.count_fac_per_people.each do | p | %>
    <p> <%= "A la persona, #{p.name}, se le facturó #{p.tot_amount} facturas" %></p>
  <% end %>
<hr>
<h2>Personas a las que mas facturó por monto:</h2>
  <% @client.fac_per_people.each do | p | %>
    <p> <%= "A la persona, #{p.name}, se le facturó un total de #{p.sum_amount} pesos"  %></p>
  <% end %>
<hr>
<hr>


<%= link_to 'Editar', edit_client_path(@client) %> |
<%= link_to 'Volver', clients_path %>