config/routes.rb
Rails.application.routes.draw do
  get "home", to: 'home#index'
  root "home#index"

  resources :people
  resources :clients do
    resources :contacts
    resources :invoices
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :client

  # enum kind: [ :email, :skype, :phone, :direction ]
  enum kind: { email: 0, skype: 1, phone: 2, direction: 3 }

  validates :kind, :data, :client, presence: true
  
  validates :kind, inclusion: { in: self.kinds.keys }

  validates :data, format: { 
    with: /\A([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@[a-z0-9-]+(.[a-z0-9-]+)*(.[a-z]{2,4})\z/,
    message: "%{value} no se permiten espacios ni letras especiales" }, if: "self.email?"

  validates :data, format: { 
    with: /\A([a-zA-Z0-9])+([a-zA-Z0-9\._-])*\z/,
    message: "%{value} no se permiten espacios ni letras especiales" }, if: "self.skype?"

  validates :data, format: { 
    with: /\A[\+0-9\-][0-9]{7,15}|^[\+0-9\-][0-9\-\ ]{5,19}[0-9]\z/,
    message: "%{value} Ingrese solo numeros, o +,-" }, if: "self.phone?"

  validates :data, format: { 
    with: /\A[a-zA-Z0-9+\°\(\)_\-][a-zA-Z0-9+\°\(\)_\-\ ]*\z/,
    message: "%{value} Ingrese una direccion, no se permite caracteres en blanco al principio" }, 
    if: "self.direction?"

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_client

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = @client.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = @client.contacts.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to client_contact_path(@client, @contact), notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to client_contact_path(@client, @contact), notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to client_contacts_path(@client), notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:kind, :data, :client_id)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for([@client,@contact]) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_del_contacto %><br>
    <%= f.select(:kind) do %>
      <% option = [ ["email", "email"], ["skype", "skype"], ["telefono", "phone"], ["direccion", "direction"]  ] %>
      <%= options_for_select(option) %>
    <% end %>

  </div>
  <div class="field">
    <%= f.label :datos_del_contacto %><br>
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editar Contacto</h1>

<%= render 'form' %>

<%= link_to 'Show', client_contact_path(@client, @contact) %> |
<%= link_to 'Back', client_contacts_path(@client) %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista Contactos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo de contacto</th>
      <th>Detalle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.kind %></td>
        <td><%= contact.data %></td>
        <td><%= link_to 'Show', client_contact_path(@client, contact) %></td>
        <td><%= link_to 'Edit', edit_client_contact_path(@client, contact) %></td>
        <td><%= link_to 'Destroy', client_contact_path(@client, contact), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Contacto', new_client_contact_path(@client) %> | <%= link_to 'Volver al cliente', client_path(@client) %>

app/views/contacts/new.html.erb
<h1>Nuevo Contacto</h1>

<%= render 'form' %>

<%= link_to 'Back', client_contacts_path(@client) %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Data:</strong>
  <%= @contact.data %>
</p>


<%= link_to 'Edit', edit_client_contact_path(@client, @contact) %> |
<%= link_to 'Back', client_contacts_path(@client) %>